### ISSUE TITLE
No such file or directory when looking for cache dir

### ISSUE THREAD

**Issue by drallgood** [octopress/ink#39]
```
$ bundle exec jekyll serve -t
[...]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `block in find': No such file or directory (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `collect!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `find'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.33/lib/octopress-ink/cache.rb:33:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.33/lib/octopress-ink/cache.rb:33:in `to_a'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.33/lib/octopress-ink/cache.rb:33:in `clean'
[...]
```

**Comment by imathis** [comment]
Cool. I'm on it.

**Comment by imathis** [comment]
This should be fixed, and hopefully nothing else is still broken.

**Comment by drallgood** [comment]
Indeed it is :smile: 
Thanks for your time!!!

The only bug left on my radar is this one: octopress/pullquote-tag#1
