### ISSUE TITLE
ink v1.0.0.rc.34 is broken

### ISSUE THREAD

**Issue by mdotasia** [octopress/ink#40]
Something is broken in RC 34. It does not find includes in subfolders, I guess. This worked fine in RC 32 and 33.

```
Running Jekyll...
Configuration file: c:/Users/Thilo.Maier/Repositories/UNStats-theme/test/source/_config.yml
            Source: c:/Users/Thilo.Maier/Repositories/UNStats-theme/test/source
       Destination: c:/Users/Thilo.Maier/Repositories/UNStats-theme/test/source/_site
      Generating...
  Liquid Exception: Include failed: {% include theme:structures/snippetList.html count="2" %}. The plugin 'theme' does not have an include named 'structures/sni
ppetList.html'. in _layouts/post.html
rake aborted!
IOError: Include failed: {% include theme:structures/snippetList.html count="2" %}.
The plugin 'theme' does not have an include named 'structures/snippetList.html'.
c:/Users/Thilo.Maier/Repositories/UNStats-theme/Rakefile:25:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `read' for #<String:0x0000000750b4a8>
c:/Users/Thilo.Maier/Repositories/UNStats-theme/Rakefile:25:in `block (2 levels) in <top (required)>'
```

**Comment by imathis** [comment]
Thanks for the report. I'll have a look.

**Comment by imathis** [comment]
I just pushed RC 35 which should fix this for you. Thanks for reporting the issue!

**Comment by mdotasia** [comment]
Yes, it works. Cool! Thanks fixing this so quickly!

**Comment by imathis** [comment]
Hey, It's nice to know folks are using this stuff. Good luck with your theme. :)

**Comment by mdotasia** [comment]
This is broken again in v1.1.0.

**Comment by imathis** [comment]
Hmm. That's odd because the test seems to pass fine. Can you give me more details of your use case? Perhaps I can add another test that covers this better.

**Comment by mdotasia** [comment]
It does not seem to be related to v1.1.0. Maybe one of the Octopress plugins was updated and breaks something? Here is something that used to work and now throws an error. Checkout `master` of https://github.com/UNStats/website-theme and run `bundle` and then `bundle exec site:preview`.

I get this error (on Vagrant though):

```
  Liquid Exception: Include failed: {% include theme:head.html %}. The plugin 'theme' does not have an include named 'head.html'. in _about/index.md
rake aborted!
IOError: Include failed: {% include theme:head.html %}.
The plugin 'theme' does not have an include named 'head.html'.
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-include-tag-1.1.0/lib/octopress-include-tag.rb:40:in `rescue in render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-include-tag-1.1.0/lib/octopress-include-tag.rb:31:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:92:in `render_liquid'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:311:in `render_liquid'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:134:in `place_in_layouts'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:56:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:306:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:292:in `block (2 levels) in render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:291:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:291:in `block in render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:290:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:290:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:197:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
/vagrant/lib/tasks/build.rake:73:in `block (2 levels) in <top (required)>'
/vagrant/lib/tasks/build.rake:81:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `include' for nil:NilClass
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-ink-1.0.0/lib/octopress-ink/plugins.rb:122:in `include'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-include-tag-1.1.0/lib/octopress-include-tag.rb:32:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:92:in `render_liquid'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:311:in `render_liquid'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:134:in `place_in_layouts'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:56:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:306:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:292:in `block (2 levels) in render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:291:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:291:in `block in render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:290:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:290:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:197:in `render'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
/vagrant/lib/tasks/build.rake:73:in `block (2 levels) in <top (required)>'
/vagrant/lib/tasks/build.rake:81:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.5@website-theme/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => site:build
(See full trace by running task with --trace)
```

**Comment by imathis** [comment]
Why do you think this has something to do with the nested includes issue? The error is complaining about trying to include `head.html` which isn't a nested include: https://github.com/UNStats/website-theme/blob/master/assets/includes/head.html

**Comment by mdotasia** [comment]
It probably has nothing to do with nested includes. When I saw the error first today it happened for a nested include and I thought this was a regression. I can debug tomorrow to see what's happening. You can close this issue and I reopen another one once I found out what causes it. Do you have any idea?

**Comment by imathis** [comment]
It's really hard for me to guess. Your usage pattern is so different from what I'm expected for people who use Octopress Ink.

**Comment by mdotasia** [comment]
I did some debugging. I had this plugin configuration, which worked prior to `v1.0.0`:

```
Octopress::Ink.add_plugin(
   name: 'website-theme',
   slug: 'theme',
   assets_path: File.expand_path(File.join(File.dirname(__FILE__), '../assets')),
   type: 'theme',
   version: Website::Theme::VERSION,
   description: '',
   website: ''
```
This configuration fails here https://github.com/octopress/ink/blob/efe048b8251221486875fab61294dd0ed551b682/lib/octopress-ink.rb#L77 because the options array is accessed with a string instead of a symbol (`'type'` instead of `:type`) and the theme get type plugin assigned. That's why later on none of the layouts is found.

When I change to

```
Octopress::Ink.add_theme(
  name: 'website-theme',
  slug: 'theme',
  assets_path: File.expand_path(File.join(File.dirname(__FILE__), '../assets')),
  version: Website::Theme::VERSION,
  description: '',
  website: ''
)
```

it works, but I'm wondering if this https://github.com/octopress/ink/blob/efe048b8251221486875fab61294dd0ed551b682/lib/octopress-ink.rb#L82 should use a symbol instead of a string.

It's not clear to me whether the options hash should use symbols or strings.

**Comment by imathis** [comment]
Good catch. I'm sorry about that regression and thanks for pointing out the symbol versus string issue. I'll take a look at that tomorrow and see what I can make of it. Just to be clear are you able to build your site again with your fixes?

**Comment by mdotasia** [comment]
Yes, with the second config, build works. But the string vs. symbol issue occurs in more places and needs to be made coherent. 

Technically I think it's not a regression it just happens to throw the same error message.

**Comment by imathis** [comment]
Other than the `register_plugin` method, where else have you seen the symbol vs string issue?

**Comment by mdotasia** [comment]
I think that's it.
