### ISSUE TITLE
Missing Dependency - pry-byebug

### ISSUE THREAD

**Issue by davidized** [octopress/ink#48]
I updated the version of the ink gem to 1.0.0.rc.52 tonight and jekyll would no longer build. The output is reproduced below.

I was able to get my site to build by adding ```gem 'pry-byebug'``` to my Gemfile, so I'm assuming the dependency on pry-byebug probably just needs to be added.

```
$ bundle exec jekyll build
Configuration file: /Users/david/Repositories/davidized/_config.yml
            Source: /Users/david/Repositories/davidized
       Destination: _site
      Generating...
/Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugin/bootstrap.rb:226:in `require': cannot load such file -- pry-byebug (LoadError)
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugin/bootstrap.rb:226:in `add_meta_indexes'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugin/bootstrap.rb:149:in `inject_pages'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugin/bootstrap.rb:67:in `bootstrap_plugin'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugin.rb:73:in `register'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugins.rb:56:in `each'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/plugins.rb:56:in `register'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-ink-1.0.0.rc.52/lib/octopress-ink/jekyll/hooks.rb:13:in `post_read'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:184:in `block in read'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:183:in `each'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:183:in `read'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:49:in `process'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/david/Repositories/davidized/.bundle/bin/jekyll:16:in `load'
	from /Users/david/Repositories/davidized/.bundle/bin/jekyll:16:in `<main>'
```

**Comment by imathis** [comment]
I'm so sorry. I've just released a new version which should fix this for you.

**Comment by davidized** [comment]
Wow, that was fast. Thanks a lot!
