### ISSUE TITLE
Octopress ink crashes

### ISSUE THREAD

**Issue by davepwsmith** [octopress/ink#61]
I'm trying to use your littlefoot plugin -- but I need to make some modifications to support the way that Pandoc labels footnotes in html. I was hoping to be able to do this with `octopress ink copy`, but when I run `octopress ink list littlefoot` I get the following errors:

````
octopress ink list littlefoot
/Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- octopress-littlefoot (LoadError)
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/octopress-3.0.7/lib/octopress.rb:68:in `new'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/octopress-3.0.7/lib/octopress.rb:68:in `read_site'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/octopress-3.0.7/lib/octopress.rb:61:in `site'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/octopress-ink-1.1.4/lib/octopress-ink.rb:150:in `plugin_list'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/octopress-ink-1.1.4/lib/octopress-ink/commands/list.rb:17:in `block (2 levels) in process_command'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/davidsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/octopress-3.0.7/bin/octopress:8:in `<top (required)>'
	from /Users/davidsmith/.rbenv/versions/2.2.2/bin/octopress:23:in `load'
	from /Users/davidsmith/.rbenv/versions/2.2.2/bin/octopress:23:in `<main>'
````

**Comment by imathis** [comment]
Hmm, I'm trying to think of why this wouldn't work. Are you running this from the root of your Jekyll site? Does your site have a Gemfile? Have you tried `bundle exec octopress ink list littlefoot`?

**Comment by davepwsmith** [comment]
Ah, bundle exec works. Sorry if that seems obvious!

On 4 June 2015 20:14:38 BST, Brandon Mathis <notifications@github.com> wrote:
>Hmm, I'm trying to think of why this wouldn't work. Are you running
>this from the root of your Jekyll site? Does your site have a Gemfile?
>Have you tried `bundle exec octopress ink list littlefoot`?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/octopress/ink/issues/61#issuecomment-109016340

-- 
Sent from my phone. Please excuse my brevity.

**Comment by imathis** [comment]
Whew. Glad it was so simple.
