### ISSUE TITLE
Jekyll 3 changed site.posts from an Array to a Collection which causes deprecation warning in Ink

### ISSUE THREAD

**Issue by awatts** [octopress/ink#64]
Starting a new blog and testing generating after just init-ing things (i.e only have the automatic first post and default index.html, etc.) trying to use Jekyll 3.0.1 and Octopress 3.0.11.

Here are the gems in my _config.yml:

``` yaml
gems:
  - octopress-codefence
  - octopress-code-highlighter
  - octopress-minify-html
  - octopress-social
  - octopress-solarized
```

Running `jekyll b` yields:

```
Deprecation: Collection#empty? should be called on the #docs array directly.
                    Called by /usr/local/lib/ruby/gems/2.3.0/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:163:in `posts?'.
Deprecation: Collection#select should be called on the #docs array directly.
                    Called by /usr/local/lib/ruby/gems/2.3.0/gems/octopress-ink-1.2.1/lib/octopress-ink/plugin/bootstrap.rb:171:in `linkposts?'.
Liquid Exception: no implicit conversion of nil into String in _posts/2015-12-27-welcome-to-jekyll.markdown
```

As far as I can tell, the deprecation warnings are because of jekyll/jekyll#4055
The final line seems to be the same octopress/hooks issue as octopress/linkblog#6 (My stack trace comes down to the same ``expand_path': no implicit conversion of nil into String (TypeError)`)

**Comment by rayfaddis** [comment]
@awatts +1 on this issue.

To resolve this for myself for the time being I'm dropping back to Octopress 3.0.2 since it uses Jekyll 2.5.3 and thus doesn't have issues with the octopress-solarized or octopress-ink gems.

**Comment by e9t** [comment]
If you're using Ink 1.1.x (or specifically, 1.1.4) you can use [my forked version](https://github.com/e9t/ink/tree/fix-warning-deprecated).
All you have to do is update your `Gemfile` as follows:

    gem 'octopress-ink', git: 'git@github.com:e9t/ink.git', branch: 'fix-warning-deprecated'
